import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const packageRoot = fileURLToPath(new URL("../", import.meta.url));
const contractRoot = fileURLToPath(new URL("../../contracts/openapi/", import.meta.url));
const sourceNames = [
  "common.openapi.json",
  "identity.openapi.json",
  "alerts.openapi.json",
  "gis.openapi.json",
  "shelters.openapi.json",
];
const documents = new Map();
for (const name of sourceNames) documents.set(name, JSON.parse(await readFile(new URL(name, new URL("../../contracts/openapi/", import.meta.url)), "utf8")));

function refName(ref) {
  return ref.slice(ref.lastIndexOf("/") + 1);
}
function typeOf(schema = {}) {
  if (schema.$ref) return refName(schema.$ref);
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.oneOf) return schema.oneOf.map(typeOf).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((value) => typeOf({ ...schema, type: value })).join(" | ");
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.type === "array") return `Array<${typeOf(schema.items)}> ` .trim();
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "object") return "Record<string, unknown>";
  return "string";
}
function emitSchema(name, schema) {
  if (schema.type !== "object" || !schema.properties) return `export type ${name} = ${typeOf(schema)};`;
  const required = new Set(schema.required ?? []);
  const fields = Object.keys(schema.properties).sort().map((key) =>
    `  ${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${typeOf(schema.properties[key])};`
  );
  return [`export interface ${name} {`, ...fields, "}"].join("\n");
}

const operations = [];
const schemas = [];
for (const sourceName of sourceNames) {
  const document = documents.get(sourceName);
  for (const name of Object.keys(document.components?.schemas ?? {}).sort()) {
    schemas.push(emitSchema(name, document.components.schemas[name]));
  }
  for (const route of Object.keys(document.paths ?? {}).sort()) {
    const operation = document.paths[route].get;
    if (!operation) continue;
    const responseSchema = operation.responses?.["200"]?.content?.["application/json"]?.schema;
    operations.push({ operationId: operation.operationId, route, responseType: typeOf(responseSchema) });
  }
}
const methods = operations.map(({ operationId, route, responseType }) => {
  const pathNames = [...route.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
  const params = pathNames.map((name) => `${name}: string`).join(", ");
  const expression = pathNames.reduce((value, name) => value.replace(`{${name}}`, `\${encodeURIComponent(${name})}`), route);
  return `  ${operationId}(${params}): Promise<${responseType}> { return this.get(\`${expression}\`); }`;
});
const generated = `// @generated by scripts/generate.mjs from OpenAPI 0.1.0. DO NOT EDIT.\n// Sources: ${sourceNames.join(", ")}\n\n${schemas.join("\n\n")}\n\nexport interface SafeZoneClientOptions {\n  baseUrl: string;\n  fetch?: typeof globalThis.fetch;\n}\n\nexport class SafeZoneClient {\n  private readonly baseUrl: string;\n  private readonly fetchImplementation: typeof globalThis.fetch;\n\n  constructor(options: SafeZoneClientOptions) {\n    this.baseUrl = options.baseUrl.replace(/\\\/$/, "");\n    this.fetchImplementation = options.fetch ?? globalThis.fetch;\n  }\n\n${methods.join("\n")}\n\n  private async get<T>(path: string): Promise<T> {\n    const response = await this.fetchImplementation(this.baseUrl + path, { headers: { accept: "application/json" } });\n    if (!response.ok) throw new Error(\`SafeZone HTTP \${response.status}\`);\n    return response.json() as Promise<T>;\n  }\n}\n`;
const target = fileURLToPath(new URL("../src/index.ts", import.meta.url));
if (process.argv.includes("--check")) {
  let current = "";
  try { current = await readFile(target, "utf8"); } catch {}
  if (current !== generated) {
    console.error("Generated SDK is out of sync. Run npm run generate.");
    process.exitCode = 1;
  }
} else {
  await writeFile(target, generated, "utf8");
  console.log(`Generated ${target}`);
}
