// @generated by scripts/generate.mjs from OpenAPI 0.1.0. DO NOT EDIT.
// Sources: common.openapi.json, identity.openapi.json, alerts.openapi.json, gis.openapi.json, shelters.openapi.json

export interface FieldError {
  "code": string;
  "field": string;
  "message"?: string;
}

export interface IdempotencyRecord {
  "created_at": string;
  "expires_at": string;
  "key_fingerprint": string;
  "request_fingerprint": string;
  "state": "processing" | "completed" | "failed_retryable";
}

export interface LocalityScope {
  "level": "province" | "district" | "commune";
  "locality_id": OpaqueIdentifier;
}

export type OpaqueIdentifier = string;

export interface PageMetadata {
  "has_more": boolean;
  "next_cursor"?: string | string;
  "page_size": number;
}

export interface ProblemDetails {
  "code": string;
  "correlation_id": OpaqueIdentifier;
  "detail"?: string;
  "errors"?: Array<FieldError>;
  "instance"?: string;
  "status": number;
  "title": string;
  "type": string;
}

export interface IdentityProjection {
  "actor_id": OpaqueIdentifier;
  "actor_type": "citizen" | "officer" | "service";
  "display_name"?: string;
  "locality_scopes": Array<LocalityScope>;
}

export type InformationKind = "official_alert" | "system_analysis" | "community_report";

export interface OfficialAlert {
  "affected_localities"?: Array<LocalityScope>;
  "alert_id": OpaqueIdentifier;
  "content": string;
  "content_hash": string;
  "effective_at": string;
  "expires_at"?: string | string;
  "information_kind": "official_alert";
  "issued_at": string;
  "lifecycle": "issued" | "updated" | "corrected" | "cancelled" | "expired";
  "previous_version_id"?: OpaqueIdentifier | string;
  "source": OfficialAlertSource;
  "supersedes_version_id"?: OpaqueIdentifier | string;
  "version_id": OpaqueIdentifier;
  "version_number": number;
}

export interface OfficialAlertPage {
  "items": Array<OfficialAlert>;
  "page": PageMetadata;
}

export interface OfficialAlertSource {
  "authority_name": string;
  "retrieved_at": string;
  "signature_status": "valid" | "invalid" | "not_provided" | "not_checked";
  "source_id": OpaqueIdentifier;
  "source_message_id"?: OpaqueIdentifier;
  "source_uri": string;
}

export interface GisDatasetSource {
  "dataset_id": OpaqueIdentifier;
  "published_at": string;
  "source_uri": string;
  "version": OpaqueIdentifier;
}

export interface PublicGeometry {
  "coordinates": Array<string>;
  "type": "Polygon" | "MultiPolygon";
}

export interface PublicLocality {
  "dataset_source": GisDatasetSource;
  "geometry": PublicGeometry;
  "locality": LocalityScope;
  "name": string;
  "updated_at": string;
}

export interface PublicShelter {
  "freshness_status": "current" | "stale";
  "locality": LocalityScope;
  "name": string;
  "official_status": "official" | "not_official";
  "public_location_description"?: string;
  "shelter_id": OpaqueIdentifier;
  "verification": ShelterVerification;
}

export interface PublicShelterPage {
  "items": Array<PublicShelter>;
  "page": PageMetadata;
}

export interface ShelterVerification {
  "authority_name": string;
  "fresh_until": string;
  "source_uri": string;
  "verified_at": string;
}

export interface SafeZoneClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
}

export class SafeZoneClient {
  private readonly baseUrl: string;
  private readonly fetchImplementation: typeof globalThis.fetch;

  constructor(options: SafeZoneClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.fetchImplementation = options.fetch ?? globalThis.fetch;
  }

  getCurrentIdentity(): Promise<IdentityProjection> { return this.get(`/v1/identity/me`); }
  listOfficialAlerts(): Promise<OfficialAlertPage> { return this.get(`/v1/official-alerts`); }
  getOfficialAlert(alert_id: string): Promise<OfficialAlert> { return this.get(`/v1/official-alerts/${encodeURIComponent(alert_id)}`); }
  getPublicLocality(locality_id: string): Promise<PublicLocality> { return this.get(`/v1/localities/${encodeURIComponent(locality_id)}`); }
  listPublicShelters(): Promise<PublicShelterPage> { return this.get(`/v1/shelters`); }

  private async get<T>(path: string): Promise<T> {
    const response = await this.fetchImplementation(this.baseUrl + path, { headers: { accept: "application/json" } });
    if (!response.ok) throw new Error(`SafeZone HTTP ${response.status}`);
    return response.json() as Promise<T>;
  }
}
